version: '3'
services:
  rewards:
    image: severinonly/ms-rewards:latest
    init: true
    privileged: true
    network_mode: "host"
    restart: always
    environment:
      ENV IS_RUNNING_IN_DOCKER: 'true'
      TZ: 'America/Montreal'
    volumes:
      - ../src:/app/src
      - ../hooks:/app/src/hooks